### ISSUE TITLE
Module not found: Error: Can't resolve 'react/jsx-runtime'

### ISSUE THREAD

**Issue by Soulfull** [space307/effector-react-slots#18]
**Describe the bug**
Importing `effector-react-slots` in `create-react-app v5.0.0` project.
After `npm run start` getting an error
```
ERROR in ./node_modules/effector-react-slots/dist/module.js 2:0-83
Module not found: Error: Can't resolve 'react/jsx-runtime' in '/Users/soulfull/dev/product-guide/node_modules/effector-react-slots/dist'
Did you mean 'jsx-runtime.js'?
BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**Environment info**
current version of create-react-app: 5.0.0
node - 16.13.0
npm -8.1.0

**Comment by Soulfull** [comment]
Is it possible to remove "type": "module" from `package.json`?

**Comment by binjospookie** [comment]
https://github.com/facebook/create-react-app/issues/11769 :c

**Comment by binjospookie** [comment]
Try to use smth like [this](https://parceljs.org/getting-started/webapp/) for testing

**Comment by Soulfull** [comment]
It seems that this bug [does not isolated](https://github.com/facebook/react/issues/20235) in CRA. Waiting for react v18
